# Generated by Django 5.0.7 on 2024-07-11 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_user_date_of_birth'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='available_for_booking',
        ),
    ]
