# Generated by Django 5.0.7 on 2024-07-11 11:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DayOfWeek',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.IntegerField(choices=[(0, 'Понедельник'), (1, 'Вторник'), (2, 'Среда'), (3, 'Четверг'), (4, 'Пятница'), (5, 'Суббота'), (6, 'Воскресенье')], unique=True, verbose_name='День недели')),
            ],
        ),
        migrations.CreateModel(
            name='WorkSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField(verbose_name='Начало рабочего дня')),
                ('end_time', models.TimeField(verbose_name='Конец рабочего дня')),
                ('on_off', models.BooleanField(default=True, verbose_name='свободен/не свободен')),
                ('bankir', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_schedule_bankir', to=settings.AUTH_USER_MODEL, verbose_name='Банкир')),
                ('day_of_week', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.dayofweek', verbose_name='День недели')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_schedule_user', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Расписание работы',
                'verbose_name_plural': 'Расписания работы',
                'unique_together': {('user', 'day_of_week')},
            },
        ),
    ]
