# Generated by Django 5.0.6 on 2024-07-13 10:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_workschedule_bankir_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dayofweek',
            options={'ordering': ['day'], 'verbose_name': 'Рабочий день недели', 'verbose_name_plural': 'Рабочие дни недели'},
        ),
        migrations.RemoveField(
            model_name='booking',
            name='booking_date',
        ),
        migrations.AlterField(
            model_name='workschedule',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_schedule', to=settings.AUTH_USER_MODEL, verbose_name='Банкир'),
        ),
    ]
