# Generated by Django 5.0.6 on 2024-07-13 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_dayofweek_options_remove_booking_booking_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workschedule',
            name='day_of_week',
            field=models.CharField(choices=[(0, 'Понедельник'), (1, 'Вторник'), (2, 'Среда'), (3, 'Четверг'), (4, 'Пятница'), (5, 'Суббота'), (6, 'Воскресенье')], default=0, max_length=10, verbose_name='День недели'),
        ),
    ]
